#!/bin/sh

chown 0:0 -R /

mkdir -p /dev /proc /sys
mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys

dmesg -n 1
insmod chaos.ko

timeout -s KILL 60 setsid cttyhack su -s /bin/sh user

rmmod chaos
poweroff -f
