#!/bin/sh

chown 0:0 -R /

mkdir -p /dev /proc /sys /tmp
mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs none /tmp

insmod chaos.ko
chmod 0666 /dev/chaos

timeout -s KILL 60 setsid cttyhack su -s /tests/go user

rmmod chaos
poweroff -f
