#!/bin/sh

chown 0:0 -R /

mkdir -p /dev /proc /sys
mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys

insmod chaos.ko
chmod 0666 /dev/chaos
dmesg -n 1

timeout -s KILL 60 setsid cttyhack su -s /tests/go.sh user

rmmod chaos
poweroff -f
